IDE-1021 Language reference files for salt need to be uppercase
hpcc-systems/eclide pull request #528
Opened 2021-06-14 17:56 UTC by dehilsterlexis

Signed-off-by: David de Hilster <david.dehilster@lexisnexis.com>

2021-06-14 17:56 UTC, dehilsterlexis commented
@GordonSmith for review

2021-06-30 14:14 UTC, GordonSmith requested changes
@dehilsterlexis can you rebase this for 8.2?

2021-06-30 14:53 UTC, dehilsterlexis commented
@GordonSmith for review

2021-06-30 14:56 UTC, GordonSmith approved these changes

2021-06-30 15:05 UTC, merged