IDE-1018 RF_Classification crashes ECL IDE on load
hpcc-systems/eclide pull request #531
Opened 2021-07-22 15:37 UTC by dehilsterlexis

Signed-off-by: David de Hilster <david.dehilster@lexisnexisrisk.com>

2021-07-22 15:37 UTC, dehilsterlexis commented
@GordonSmith for review

2021-07-23 13:26 UTC, GordonSmith requested changes
Rebase onto 8.2.x

2021-07-23 13:57 UTC, dehilsterlexis commented
@GordonSmith rebased

2021-07-26 08:17 UTC, GordonSmith approved these changes

2021-07-26 08:54 UTC, merged