IDE-974 Opening read-only files from a Find (Repository) incorrectly
hpcc-systems/eclide pull request #543
Opened 2022-04-27 19:48 UTC by dehilsterlexis

Signed-off-by: David de Hilster <david.dehilster@lexisnexisrisk.com>

2022-04-27 19:48 UTC, dehilsterlexis commented
@GordonSmith for review

2022-05-09 09:32 UTC, GordonSmith requested changes

2022-05-09 14:52 UTC, dehilsterlexis commented
@GordonSmith for review

2022-05-10 06:37 UTC, GordonSmith approved these changes

2022-05-10 09:31 UTC, merged