HPCC-31249 Add HINTS for clienttools location for build-assets builds
hpcc-systems/eclide pull request #561
Opened 2024-02-12 15:44 UTC by Michael-Gardner

2024-02-12 15:45 UTC, Michael-Gardner commented on CMakeLists.txt
> +find_file(CLIENTTOOLS_PACKAGE_FILE "hpccsystems-clienttools-community_${version}-${stagever}${CMAKE_SYSTEM_NAME}-${CT_ARCH}.exe" HINTS ${CMAKE_CURRENT_BINARY_DIR}/../HPCC-Platform ${CMAKE_CURRENT_BIN
Added hints that will allow us to find the clienttools package in github actions build-asset workflow

2024-02-12 15:55 UTC, Michael-Gardner commented
Test build here:  Output for the eclide package should be +100MB https://github.com/Michael-Gardner/HPCC-Platform/actions/runs/7874284284

2024-02-14 08:25 UTC, GordonSmith requested changes

2024-02-14 08:25 UTC, GordonSmith commented on CMakeLists.txt
> +    MESSAGE(FATAL_ERROR "Could not locate hpccsystems-clienttools-community_${version}-${stagever}${CMAKE_SYSTEM_NAME}-${CT_ARCH}.exe")
This will be very inconvenient for the eclide developers...

2024-02-15 15:56 UTC, Michael-Gardner commented
@GordonSmith Removed that FATAL_ERROR message

2024-02-15 15:57 UTC, GordonSmith approved these changes

2024-02-15 15:57 UTC, merged